author_index:
    path:     /
    defaults: { _controller: "AppBundle:Author:index" }
    methods:  GET

author_show:
    path:     /{author_id}
    defaults: { _controller: "AppBundle:Author:show" }
    methods:  GET

author_new:
    path:     /
    defaults: { _controller: "AppBundle:Author:new" }
    methods:  POST

author_edit:
    path:     /{author_id}
    defaults: { _controller: "AppBundle:Author:edit" }
    methods:  [POST, PUT, PATCH]

author_delete:
    path:     /{author_id}
    defaults: { _controller: "AppBundle:Author:delete" }
    methods:  DELETE
