quote_index:
    path:     /quote
    defaults: { _controller: "AppBundle:Quote:index" }
    methods:  GET

quote_show:
    path:     /author/{author_id}
    defaults: { _controller: "AppBundle:Quote:show" }
    methods:  GET

quote_pull:
    path:     /quote/{quote_id}
    defaults: { _controller: "AppBundle:Quote:pull" }
    methods:  GET

quote_new:
    path:     /quote
    defaults: { _controller: "AppBundle:Quote:new" }
    methods:  [POST]

quote_edit:
    path:     /quote/{quote_id}
    defaults: { _controller: "AppBundle:Quote:edit" }
    methods:  [POST, PUT, PATCH]

quote_delete:
    path:     /quote/{quote_id}
    defaults: { _controller: "AppBundle:Quote:delete" }
    methods:  DELETE

quote_random:
    path:     /quoteRandom
    defaults: { _controller: "AppBundle:Quote:random" }
    methods:  GET
